Tech absolute paths
ManelSoria/HGSpy pull request #2
Opened 2024-05-07 12:59 UTC by CalebFuster

2024-05-07 14:32 UTC, ArnauMiro requested changes
Jo això dels paths absoluts no ho veig gens

2024-05-07 14:32 UTC, ArnauMiro commented on .gitignore
Already on the previous commit

2024-05-07 14:32 UTC, ArnauMiro commented on HGSpy/__init__.py
Quin avantantge hi ha en fer-ho així? Es liaran tots els paths i ja funcionava, perquè tocar-ho?

2024-05-07 16:37 UTC, CalebFuster commented on HGSpy/__init__.py
Legibilitat, si un projecte es fa gran saber a quin arxui esta apuntant de manera directa es molt mes agradable, amb punts es molt contra intuitiu i poc clar. 

Els absolut path mai lien res, tret que creis python scripts dintre del  src de la llibreria (cosa que mai s'hauria de fer) o si importes path en un altre projecte (com si fos Matlab que es una idea horrible, sobretot tenint wheels)

2024-05-08 06:56 UTC, ArnauMiro commented on HGSpy/__init__.py
Bé, jo veig més clar els relatius, és un tema personal. Si vols deixar els absoluts no tinc problema.

2024-05-08 06:56 UTC, ArnauMiro approved these changes

2024-05-08 08:55 UTC, merged