Tech adding unit testing
ManelSoria/HGSpy pull request #3
Opened 2024-05-07 12:59 UTC by CalebFuster

2024-05-07 14:37 UTC, ArnauMiro requested changes
Està bé això dels unity tests pero potser el que has muntat es un overkill pel que ha de ser la llibreria

2024-05-07 14:37 UTC, ArnauMiro commented on HGSpy/cr.py
Que ha passat aqui, això potser hauria d'anar a part

2024-05-07 14:37 UTC, ArnauMiro commented on .gitignore
En un altre commit

2024-05-07 16:41 UTC, CalebFuster commented on HGSpy/cr.py
Es el autoformater. La majoria dels fitxers mesclen tabs i spaces cosa que python no aprova en el seu pip8.

El unic canvi es el env check pq fer patch the decorador no ho he conseguit

2024-05-07 16:44 UTC, CalebFuster commented
> Està bé això dels unity tests pero potser el que has muntat es un overkill pel que ha de ser la llibreria

Si be es un overkill, cualsevol canvi ara es pot validar abans de fer-ne push. No tenir testing que validi que no es trenqui codis antics o almenos saber que ho has trencat, es un perill.

2024-05-08 06:56 UTC, ArnauMiro approved these changes

2024-05-08 06:56 UTC, ArnauMiro commented on HGSpy/cr.py
Això no podria anar amb un merge particular? Aquí estem parlant d'altres coses...

2024-05-08 06:58 UTC, ArnauMiro commented
Saps posar-ho en un workflow?
N'hi ha un de creat, run_examples, que precisament serveix per això.

2024-05-08 08:36 UTC, CalebFuster commented on HGSpy/cr.py
Esta canviat ja, m´ha costat que no faci format automatic pero ara nomes tye el canvi del unittesting

2024-05-08 08:37 UTC, CalebFuster commented
Si puc posar el workflow en un segon

2024-05-08 09:05 UTC, ArnauMiro approved these changes

2024-05-08 14:46 UTC, merged